import fs from 'fs';

// This script safely moves the output generated by Nitro from `dist` to `.vercel/output`
// which Vercel's Build Engine natively understands.
if (fs.existsSync('dist/config.json')) {
  fs.rmSync('.vercel', { recursive: true, force: true });
  fs.mkdirSync('.vercel/output', { recursive: true });
  
  if (fs.existsSync('dist/client')) {
    fs.cpSync('dist/client', '.vercel/output/static', { recursive: true });
  }
  if (fs.existsSync('dist/server')) {
    fs.cpSync('dist/server', '.vercel/output/functions', { recursive: true });
  }
  if (fs.existsSync('dist/config.json')) {
    fs.copyFileSync('dist/config.json', '.vercel/output/config.json');
  }
  console.log('Successfully prepared .vercel/output directory for Vercel deployment');
} else {
  console.log('No dist/config.json found. Skipping Vercel output preparation.');
}
